# Generated by Django 5.2.1 on 2025-07-15 10:33

import django.db.models.deletion
import publics.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=publics.models.save_avatar_to, verbose_name='аватар пользователя')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('is_private', models.BooleanField(default=False, verbose_name='приватный паблик')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('members', models.ManyToManyField(related_name='member_of_publics', to=settings.AUTH_USER_MODEL, verbose_name='участники')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_publics', to=settings.AUTH_USER_MODEL, verbose_name='владелец паблика')),
            ],
            options={
                'verbose_name': 'паблик',
                'verbose_name_plural': 'паблики',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PublicInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата приглашения')),
                ('accepted', models.BooleanField(default=None, null=True, verbose_name='принято')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL, verbose_name='кем приглашен')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('public', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_invites', to='publics.public', verbose_name='паблик')),
            ],
            options={
                'verbose_name': 'приглашение в паблик',
                'verbose_name_plural': 'приглашения в паблики',
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('public', 'invited_user', 'invited_by'), name='unique_public_invite')],
            },
        ),
    ]
