# Generated by Django 5.2.1 on 2025-07-15 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_gallery', to='publics.public', verbose_name='паблик')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_gallery', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('images', models.ManyToManyField(related_name='gallery_images', to='images.images', verbose_name='изображения')),
            ],
            options={
                'verbose_name': 'галлерея',
                'verbose_name_plural': 'галлереи',
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('public__isnull', True)), models.Q(('user__isnull', True), ('public__isnull', False)), _connector='OR'), name='only_user_or_public')],
            },
        ),
    ]
