# Generated by Django 5.2.1 on 2025-07-15 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group', models.BooleanField(default=False, verbose_name='групповой чат')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='заголовок')),
                ('users', models.ManyToManyField(related_name='users_chats', to=settings.AUTH_USER_MODEL, verbose_name='пользователи')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='текст')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлено')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chats.chat', verbose_name='чат')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_message', to='chats.message', verbose_name='ответ на...')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sender', to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(condition=models.Q(('is_group', False), models.Q(('is_group', True), ('title__isnull', False)), _connector='OR'), name='group_chat_requires_title'),
        ),
    ]
